# File: .github/workflows/workflow.yml

on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps: 
    - uses: actions/checkout@v2
    - uses: tibor19/static-website-deploy@v1
      with:
        enabled-static-website: 'true'
        folder: 'files'
        connection-string: ${{ secrets.CONNECTION_STRING }}